# Generated by Django 5.0.3 on 2024-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="csection",
            field=models.BooleanField(default=False),
        ),
    ]
