# Generated by Django 5.0.3 on 2024-04-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_entry_csection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="classification",
            field=models.CharField(
                choices=[
                    ("1", "Group 1"),
                    ("2", "Group 2"),
                    ("3", "Group 3"),
                    ("4", "Group 4"),
                    ("5", "Group 5"),
                    ("6", "Group 6"),
                    ("7", "Group 7"),
                    ("8", "Group 8"),
                    ("9", "Group 9"),
                    ("10", "Group 10"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "Entries"},
        ),
        migrations.DeleteModel(
            name="Classification",
        ),
    ]
