# Generated by Django 5.0.3 on 2024-04-03 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_alter_entry_classification_alter_entry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="hospital",
        ),
    ]
