# Generated by Django 5.0.3 on 2024-04-03 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrator",
            options={"verbose_name_plural": "Administrators"},
        ),
        migrations.AlterModelOptions(
            name="baseuser",
            options={"verbose_name_plural": "Base Users"},
        ),
    ]
